/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Saúde da API e do banco */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                        };
                    };
                };
                /** @description Default Response */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "unavailable";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login com e-mail e senha
         * @description Define o cookie de sessão `sid`. Exige o header `X-Requested-With: gex-web`. Limite de tentativas por IP e por e-mail.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Corpo ilegível (JSON quebrado) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Sessão ausente/expirada ou credenciais inválidas */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Perfil sem permissão ou header anti-CSRF ausente */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Dados inválidos (erro por campo em `errors`) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Muitas tentativas de login */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Encerra a sessão
         * @description Exige o header `X-Requested-With: gex-web`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sessão encerrada */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Sessão ausente/expirada ou credenciais inválidas */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Perfil sem permissão ou header anti-CSRF ausente */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuário da sessão e data de referência do servidor */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                /** @description Sessão ausente/expirada ou credenciais inválidas */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista paginada com filtros
         * @description REQUESTER vê só as próprias; FINANCE vê todas. Filtros e paginação aplicados no banco.
         */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["RequestStatusInput"];
                    supplier?: string;
                    /** @description Data de negócio no formato YYYY-MM-DD, sem fuso */
                    due_from?: string;
                    /** @description Data de negócio no formato YYYY-MM-DD, sem fuso */
                    due_to?: string;
                    page?: number;
                    page_size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RequestList"];
                    };
                };
                /** @description Sessão ausente/expirada ou credenciais inválidas */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Dados inválidos (erro por campo em `errors`) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Cria uma solicitação (REQUESTER)
         * @description Responde 201 com `Location`. Exige o header `X-Requested-With: gex-web`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        supplier_name: string;
                        supplier_cnpj: string;
                        invoice_number: string;
                        amount_cents: number;
                        /** @description Mês de competência, YYYY-MM */
                        competence: string;
                        /**
                         * Format: date
                         * @description Data de negócio no formato YYYY-MM-DD, sem fuso
                         */
                        due_date: string;
                        category: components["schemas"]["CategoryInput"];
                        description?: string | null;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RequestDetail"];
                    };
                };
                /** @description Corpo ilegível (JSON quebrado) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Sessão ausente/expirada ou credenciais inválidas */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Perfil sem permissão ou header anti-CSRF ausente */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Nota duplicada ou transição inválida */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Dados inválidos (erro por campo em `errors`) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe com histórico */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RequestDetail"];
                    };
                };
                /** @description Sessão ausente/expirada ou credenciais inválidas */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Não encontrado, de outra pessoa ou id inválido */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aprova ou rejeita uma solicitação pendente (FINANCE)
         * @description Rejeitar exige `reason`. Exige o header `X-Requested-With: gex-web`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        decision: "APPROVE";
                    } | {
                        /** @enum {string} */
                        decision: "REJECT";
                        reason: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RequestDetail"];
                    };
                };
                /** @description Corpo ilegível (JSON quebrado) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Sessão ausente/expirada ou credenciais inválidas */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Perfil sem permissão ou header anti-CSRF ausente */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Não encontrado, de outra pessoa ou id inválido */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Nota duplicada ou transição inválida */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Dados inválidos (erro por campo em `errors`) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{id}/mark-paid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registra o pagamento de uma solicitação aprovada (FINANCE)
         * @description `paid_at` não pode ser futuro nem anterior à aprovação. Exige o header `X-Requested-With: gex-web`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: date-time
                         * @description Instante RFC 3339
                         */
                        paid_at: string;
                        payment_reference: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RequestDetail"];
                    };
                };
                /** @description Corpo ilegível (JSON quebrado) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Sessão ausente/expirada ou credenciais inválidas */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Perfil sem permissão ou header anti-CSRF ausente */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Não encontrado, de outra pessoa ou id inválido */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Nota duplicada ou transição inválida */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Dados inválidos (erro por campo em `errors`) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Indicadores (escopo pelo perfil)
         * @description REQUESTER: só as próprias solicitações. FINANCE: todas.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardSummary"];
                    };
                };
                /** @description Sessão ausente/expirada ou credenciais inválidas */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        RequestStatusInput: "PENDING" | "APPROVED" | "REJECTED" | "PAID";
        /** @enum {string} */
        CategoryInput: "INFRAESTRUTURA" | "MARKETING" | "SERVIÇOS" | "SOFTWARE";
        /** @enum {string} */
        RoleInput: "REQUESTER" | "FINANCE";
        UserRefInput: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        ProblemInput: {
            type: string;
            title: string;
            status: number;
            detail: string;
            /** @enum {string} */
            code: "VALIDATION_FAILED" | "INVALID_CREDENTIALS" | "UNAUTHENTICATED" | "FORBIDDEN" | "NOT_FOUND" | "DUPLICATE_INVOICE" | "INVALID_TRANSITION" | "TOO_MANY_REQUESTS" | "INTERNAL";
            errors?: {
                field: string;
                message: string;
            }[];
        };
        UserInput: {
            /** Format: uuid */
            id: string;
            name: string;
            email: string;
            role: components["schemas"]["RoleInput"];
        };
        LoginResponseInput: {
            user: components["schemas"]["UserInput"];
        };
        MeInput: {
            user: components["schemas"]["UserInput"];
            /**
             * Format: date
             * @description Data de negócio no formato YYYY-MM-DD, sem fuso
             */
            reference_date: string;
        };
        DashboardSummaryInput: {
            pending_amount_cents: number;
            approved_amount_cents: number;
            paid_this_month_amount_cents: number;
            overdue_count: number;
            /**
             * Format: date
             * @description Data de negócio no formato YYYY-MM-DD, sem fuso
             */
            reference_date: string;
        };
        RequestListItemInput: {
            /** Format: uuid */
            id: string;
            supplier_name: string;
            invoice_number: string;
            amount_cents: number;
            /**
             * Format: date
             * @description Data de negócio no formato YYYY-MM-DD, sem fuso
             */
            due_date: string;
            status: components["schemas"]["RequestStatusInput"];
            is_overdue: boolean;
            requester: components["schemas"]["UserRefInput"];
        };
        RequestListInput: {
            data: components["schemas"]["RequestListItemInput"][];
            page: number;
            page_size: number;
            total: number;
            total_pages: number;
            /**
             * Format: date
             * @description Data de negócio no formato YYYY-MM-DD, sem fuso
             */
            reference_date: string;
        };
        HistoryEventInput: {
            /** Format: uuid */
            id: string;
            previous_status: components["schemas"]["RequestStatusInput"] | null;
            new_status: components["schemas"]["RequestStatusInput"];
            actor: components["schemas"]["UserRefInput"];
            reason: string | null;
            /**
             * Format: date-time
             * @description Instante RFC 3339
             */
            created_at: string;
        };
        RequestDetailInput: {
            /** Format: uuid */
            id: string;
            requester: components["schemas"]["UserRefInput"];
            supplier_name: string;
            supplier_cnpj: string;
            invoice_number: string;
            amount_cents: number;
            /** @description Mês de competência, YYYY-MM */
            competence: string;
            /**
             * Format: date
             * @description Data de negócio no formato YYYY-MM-DD, sem fuso
             */
            due_date: string;
            category: components["schemas"]["CategoryInput"];
            description: string | null;
            status: components["schemas"]["RequestStatusInput"];
            is_overdue: boolean;
            rejection_reason: string | null;
            paid_at: string | null;
            payment_reference: string | null;
            /**
             * Format: date-time
             * @description Instante RFC 3339
             */
            created_at: string;
            /**
             * Format: date-time
             * @description Instante RFC 3339
             */
            updated_at: string;
            history: components["schemas"]["HistoryEventInput"][];
        };
        /** @enum {string} */
        RequestStatus: "PENDING" | "APPROVED" | "REJECTED" | "PAID";
        /** @enum {string} */
        Category: "INFRAESTRUTURA" | "MARKETING" | "SERVIÇOS" | "SOFTWARE";
        /** @enum {string} */
        Role: "REQUESTER" | "FINANCE";
        UserRef: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        Problem: {
            type: string;
            title: string;
            status: number;
            detail: string;
            /** @enum {string} */
            code: "VALIDATION_FAILED" | "INVALID_CREDENTIALS" | "UNAUTHENTICATED" | "FORBIDDEN" | "NOT_FOUND" | "DUPLICATE_INVOICE" | "INVALID_TRANSITION" | "TOO_MANY_REQUESTS" | "INTERNAL";
            errors?: {
                field: string;
                message: string;
            }[];
        };
        User: {
            /** Format: uuid */
            id: string;
            name: string;
            email: string;
            role: components["schemas"]["Role"];
        };
        LoginResponse: {
            user: components["schemas"]["User"];
        };
        Me: {
            user: components["schemas"]["User"];
            /**
             * Format: date
             * @description Data de negócio no formato YYYY-MM-DD, sem fuso
             */
            reference_date: string;
        };
        DashboardSummary: {
            pending_amount_cents: number;
            approved_amount_cents: number;
            paid_this_month_amount_cents: number;
            overdue_count: number;
            /**
             * Format: date
             * @description Data de negócio no formato YYYY-MM-DD, sem fuso
             */
            reference_date: string;
        };
        RequestListItem: {
            /** Format: uuid */
            id: string;
            supplier_name: string;
            invoice_number: string;
            amount_cents: number;
            /**
             * Format: date
             * @description Data de negócio no formato YYYY-MM-DD, sem fuso
             */
            due_date: string;
            status: components["schemas"]["RequestStatus"];
            is_overdue: boolean;
            requester: components["schemas"]["UserRef"];
        };
        RequestList: {
            data: components["schemas"]["RequestListItem"][];
            page: number;
            page_size: number;
            total: number;
            total_pages: number;
            /**
             * Format: date
             * @description Data de negócio no formato YYYY-MM-DD, sem fuso
             */
            reference_date: string;
        };
        HistoryEvent: {
            /** Format: uuid */
            id: string;
            previous_status: components["schemas"]["RequestStatus"] | null;
            new_status: components["schemas"]["RequestStatus"];
            actor: components["schemas"]["UserRef"];
            reason: string | null;
            /**
             * Format: date-time
             * @description Instante RFC 3339
             */
            created_at: string;
        };
        RequestDetail: {
            /** Format: uuid */
            id: string;
            requester: components["schemas"]["UserRef"];
            supplier_name: string;
            supplier_cnpj: string;
            invoice_number: string;
            amount_cents: number;
            /** @description Mês de competência, YYYY-MM */
            competence: string;
            /**
             * Format: date
             * @description Data de negócio no formato YYYY-MM-DD, sem fuso
             */
            due_date: string;
            category: components["schemas"]["Category"];
            description: string | null;
            status: components["schemas"]["RequestStatus"];
            is_overdue: boolean;
            rejection_reason: string | null;
            paid_at: string | null;
            payment_reference: string | null;
            /**
             * Format: date-time
             * @description Instante RFC 3339
             */
            created_at: string;
            /**
             * Format: date-time
             * @description Instante RFC 3339
             */
            updated_at: string;
            history: components["schemas"]["HistoryEvent"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
